### ISSUE TITLE
Missing helper functions

### ISSUE THREAD

**Issue by edefalco** [rutishauserlab/cellclassifier#1]
Hi, 
thanks for sharing this repository! 
I have tried to test it, but it seems that some of the helper functions called in the classify_EAPs_main.m are missing (e.g. cutDataVec, upsampleSpikes, realigneSpikes, fitCardiacModulation). 
Does this repository depend on other packages? 

Thanks,
Emanuela

**Comment by cpmosh** [comment]
Hi Emanuela,

Glad you're trying to use this tool!  Thanks for bringing this to our attention.

I've just uploaded the helper functions you listed (sorry for missing them earlier!).

In addition to these you'll need some functions from the circular statistics toolbox by Philipp Berens.  You can download that here: https://www.mathworks.com/matlabcentral/fileexchange/10676-circular-statistics-toolbox-directional-statistics

I will double check now if there are any other functions you might need and upload.

Thanks,
Clayton

--Clayton

**Comment by edefalco** [comment]
Hi Clayton,

thank you so much! This is a very nice tool, greatly appreciated.

I'll let you know in case I miss any other function.

Cheers,
Emanuela
