### ISSUE TITLE
Missing link exampleData.mat

### ISSUE THREAD

**Issue by frankdopamine** [rutishauserlab/cellclassifier#2]
Hi, the dropbox link to download the sample data has been deleted (https://www.dropbox.com/s/iaqq9sjozv7tnv3/exampleData.mat?dl=0). 
Could you provide a new working link?
Thank you

**Comment by cpmosh** [comment]
Hi, thanks for letting us know! Recently the data was moved because of space issues with dropbox.  A new Box link has been added to the ReadMe.  You can accesss the data here: https://cedars.box.com/s/uzshc4mqdk3adtlxeb5dekudjafw3f87
